### ISSUE TITLE
Integration test on Team city not getting rich test information

### ISSUE THREAD

**Issue by laitang2000** [g0t4/aspnetcore-generator-api#9]
I'm following your course on PS and I'm trying to get the Integration Test displaying test information.

This is my docker-compose.yml file
```
version: '3.1'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
    #ports:
    #  - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
    #  - "8025:8025"
  integration:
    image: my-registry:55000/gen:integration-${BUILD_NUMBER-10}
    build: .
     - TEAMCITY_PROJECT_NAME: fake
```

I'm trying to set TEAMCITY_PROJECT_NAME to fake  but team city is refusing to show rich test information from xnunit. Any suggestions?

Thanks
